### PR TITLE
Presentation Mode

### PR DESCRIPTION
**Pull request by guggero**
This is a quick and dirty implementation of #4.

I really love the idea of this library! It looks awesome and is exactly what I was looking for.
The presentation mode is a great idea, I was going to implement something like that anyway.
So why not build it more or less like you suggested in the issue :-)
I'm going to add keyboard navigation and the ability to go back one step in a later PR.

I also did some cleaning up and formatting, I hope you don't mind.

### CODE REVIEW

**Comment by mojoaxel** [comment]
@guggero Is there a reason why you changes every double quote to a single quote? That makes reviewing your changes quite hard. Maybe you can change that back and maybe create a new pull request for this (if you have to)??

**Comment by mojoaxel** [comment]
Thx! 
I'm ok with merging this but there are still a lot of "style" fixes in this. Maybe you can move them also to a "code cleanup" pull-request?

If you don't want to do that extra work I'll merge your PR later anyway, but I would prefer "clean" pull-requests ;-)


I usually use different quote types for different thinks but I'm ok with generalizing them so that we can better work together.

**Comment by guggero** [comment]
My IDE is removing all the superfluous white space... I'll try to fix it. Should only take a few minutes.
I prefer clean PRs too! Should have checked the commits again before pushing.

I see your point about using different quote types for different things.
But to be honest, I don't see the difference between

```javascript
	updateSimulationCenter() {
		const centerX = this.svg.attr('width') / 2;
		const centerY = this.svg.attr('height') / 2;
```

and

```javascript
		var nodeParent = this._nodeElements.enter().append("g")
			.attr("class", "node")
			.attr("id", (data) => data.id)
			.attr("balance", (data) => data.balance)
```
Maybe there's a logic I don't see.
I don't want to impose on your code style.

**Comment by mojoaxel** [comment]
:-) there was no logic there. That's just due to copy past I assume...That would be an example:
```js
data = {
 "key": value['key'] || "value"
}
```

**Comment by guggero** [comment]
Ok :sweat_smile: 
So should I change everything to double quotes in the cleanup PR?

**Comment by mojoaxel** [comment]
I'm ok with double quotes everywhere.

**Comment by mojoaxel** [comment]
@guggero Somethink went wrong here! The global gefinition on `COMMAND_MAPPING` is missing now.

**Pull request merged**
