### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by guggero**
A few basic code health issues:

* Add missing tags in HTML files
* Remove superfluous white spaces
* Add JSDoc comments and use consistent newlines
* Use double quotes everywhere
* Use `===` operator everywhere
* Use `let` keyword everywhere
* Use semicolon everywhere
* Fix some typos

If you don't agree with any change, feel free to say so. I can update the PR.

### CODE REVIEW

**Comment by mojoaxel** [comment]
@guggero can you please update this to the current master! thx!

**Comment by guggero** [comment]
Done!

**Comment by mojoaxel** [comment]
Thx. We now have also `rpm run beautify` :-)

**Comment by guggero** [comment]
nice :-)

**Pull request merged**
